version: '3.1'
name: "TesloNest"
services:
  database:
    container_name: teslodb
    image: postgres:14.3
    # restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  tesloVolume:
